// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ednzvqjxuqwfnzhrhydb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkbnp2cWp4dXF3Zm56aHJoeWRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4OTk3OTksImV4cCI6MjA2NzQ3NTc5OX0.UlqspmBN0CbctJQP6c0f38w8cIDK7eykUqj8Tb4iKXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});